In [ ]:
import pandas as pd
df = pd.read_csv("../data/clean_data.csv", comment='#')

In [ ]:
df2 = df[(df['pl_orbsmax'] >= 0.1) & (df['pl_orbsmax'] <=0.3)]
df2.to_csv(r"../outputs/insights.csv", index=False)

In [ ]:
df3=df2[(df2['pl_insol'] >= 0.5) & (df2['pl_insol'] <= 1.5)]
df3.to_csv(r"../outputs/insights.csv", index=False)

In [4]:
df3

,rowid,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,default_flag,...,rowupdate,pl_pubdate,releasedate,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
40,5174,K2-3 d,K2-3,d,NaN,NaN,TIC 173103335,Gaia DR2 3796690380302214272,Gaia DR3 3796690380302214272,0,...,2020-05-04,2016-08,2016-07-07,4.0,0.0,0.0,0.0,0.0,2.0,0.0
42,5176,K2-3 d,K2-3,d,NaN,NaN,TIC 173103335,Gaia DR2 3796690380302214272,Gaia DR3 3796690380302214272,1,...,2023-07-10,2022-11,2023-07-10,4.0,0.0,0.0,0.0,0.0,2.0,0.0
194,37126,TOI-700 d,TOI-700,d,NaN,NaN,TIC 150428135,Gaia DR2 5284517766615492736,Gaia DR3 5284517766615850752,1,...,2023-01-18,2023-01,2023-01-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0
195,37127,TOI-700 d,TOI-700,d,NaN,NaN,TIC 150428135,Gaia DR2 5284517766615492736,Gaia DR3 5284517766615850752,0,...,2020-07-17,2020-09,2020-07-23,1.0,0.0,0.0,0.0,0.0,0.0,0.0
196,37129,TOI-700 e,TOI-700,e,NaN,NaN,TIC 150428135,Gaia DR2 5284517766615492736,Gaia DR3 5284517766615850752,1,...,2023-01-18,2023-01,2023-01-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
df3

,rowid,pl_name,hostname,pl_letter,hd_name,hip_name,tic_id,gaia_dr2_id,gaia_dr3_id,default_flag,...,rowupdate,pl_pubdate,releasedate,pl_nnotes,st_nphot,st_nrvc,st_nspec,pl_nespec,pl_ntranspec,pl_ndispec
40,5174,K2-3 d,K2-3,d,NaN,NaN,TIC 173103335,Gaia DR2 3796690380302214272,Gaia DR3 3796690380302214272,0,...,2020-05-04,2016-08,2016-07-07,4.0,0.0,0.0,0.0,0.0,2.0,0.0
42,5176,K2-3 d,K2-3,d,NaN,NaN,TIC 173103335,Gaia DR2 3796690380302214272,Gaia DR3 3796690380302214272,1,...,2023-07-10,2022-11,2023-07-10,4.0,0.0,0.0,0.0,0.0,2.0,0.0
194,37126,TOI-700 d,TOI-700,d,NaN,NaN,TIC 150428135,Gaia DR2 5284517766615492736,Gaia DR3 5284517766615850752,1,...,2023-01-18,2023-01,2023-01-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0
195,37127,TOI-700 d,TOI-700,d,NaN,NaN,TIC 150428135,Gaia DR2 5284517766615492736,Gaia DR3 5284517766615850752,0,...,2020-07-17,2020-09,2020-07-23,1.0,0.0,0.0,0.0,0.0,0.0,0.0
196,37129,TOI-700 e,TOI-700,e,NaN,NaN,TIC 150428135,Gaia DR2 5284517766615492736,Gaia DR3 5284517766615850752,1,...,2023-01-18,2023-01,2023-01-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0